# Generated by Django 3.1.6 on 2021-11-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20211105_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='1', max_length=45, verbose_name='apellido'),
            preserve_default=False,
        ),
    ]
