# Generated by Django 3.1.6 on 2021-11-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_team_number'),
        ('patients', '0004_auto_20211105_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='medico'),
        ),
    ]
