# Generated by Django 3.1.6 on 2021-11-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_team_number'),
        ('patients', '0004_auto_20211105_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffering', models.CharField(max_length=45, unique=True, verbose_name='padecimiento')),
                ('diagnosis', models.CharField(max_length=45, verbose_name='diagnostico')),
                ('treatment', models.CharField(blank=True, max_length=45, null=True, verbose_name='tratamiento')),
                ('analysis', models.CharField(max_length=45, verbose_name='analisis realizados')),
                ('results', models.CharField(max_length=45, verbose_name='resultados de analisis')),
                ('doctor', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='medico')),
                ('patient', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'Historial Medico',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
