# Generated by Django 3.1.6 on 2021-11-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historial Medico', 'verbose_name_plural': 'Historiales Medicos'},
        ),
    ]
