# Generated by Django 3.1.6 on 2021-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20211105_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='suffering',
            field=models.CharField(max_length=45, verbose_name='padecimiento'),
        ),
    ]
