# Generated by Django 3.1.6 on 2021-11-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('specialty', models.CharField(max_length=45, verbose_name='especialidad')),
                ('certificate', models.CharField(max_length=45, verbose_name='cedula profesional')),
                ('university', models.CharField(max_length=45, verbose_name='universidad')),
                ('affiliation', models.CharField(max_length=45, verbose_name='afiliacion')),
            ],
            options={
                'verbose_name': 'Registro Medico',
                'verbose_name_plural': 'Registros de Medicos',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ManyToManyField(related_name='doctors', to='doctor.Doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Registro Medico',
                'verbose_name_plural': 'Registros de Medicos',
            },
        ),
    ]
