# Generated by Django 3.1.6 on 2021-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Medico', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipo de Trabajo'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='affiliation',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='afiliacion'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.CharField(max_length=45, unique=True, verbose_name='cedula profesional'),
        ),
    ]
